version: '3.4'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: jfrog_artifactory
    ports:
     - 8081:8081
     - 8086:8082
    volumes:
     - /path/to/certs:/artifactory_extra_certs
    restart: always
